spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url:
#    username:
#    password:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"   #允许访问的客户端域名
            allowedMethods: "*"   #允许访问的方法名,GET POST等
            allowedHeaders: "*"    #/*允许服务端访问的客户端请求头*/
            allowCredentials: true  #/*是否允许请求带有验证信息*/
            MaxAge: 18000   #预检请求的缓存时间（秒），即在这个时间段里，对于相同的跨域请求不会再预检了

eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      zone-1: http://localhost:8761/eureka/