spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB


server:
  port: 8080
  compression:
    enabled: true






