spring:
  datasource:
    oa:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://120.27.69.126:3306/istic-oa?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: MyNewPass4!
        hikari:
          connection-test-query: SELECT 1 FROM DUAL
          minimum-idle: 5
          maximum-pool-size:  30
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
    keyan:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://120.27.69.126:3306/istic-keyan?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: MyNewPass4!
        hikari:
          connection-test-query: SELECT 1 FROM DUAL
          minimum-idle: 5
          maximum-pool-size:  30
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
  redis:
    port: 9000
    password: abcd-1234
    host: 120.27.69.126


