spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.69.126:3306/istic?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: MyNewPass4!
  redis:
    port: 9000
    password: abcd-1234
    host: 120.27.69.126
server:
  port: 9001
  tomcat:
    max-http-post-size: 102400000
mybatis:
  mapperLocations: classpath:com/istic/dao/mapper/*Mapper.xml
  typeAliasesPackage: com.istic.entity
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
