eureka:
    instance:
      prefer-ip-address: true
      metadataMap:
       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
     registerWithEureka: true
     fetchRegistry: true
     prefer-same-zone-eureka: true
     region: dev
     availability-zones:
      dev: zone-1
     service-url:
       zone-1: http://localhost:8761/eureka/
    server:
      enable-self-preservation: false   #关闭自我保护机制