eureka:
    instance:
      prefer-ip-address: true
      metadataMap:
       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
     registerWithEureka: false
     fetchRegistry: false
     prefer-same-zone-eureka: true
     service-url:
       zone-1: http://localhost:8761/eureka/
    server:
      enable-self-preservation: false   #关闭自我保护机制